#ifndef INCLUDED_ETR_DEFINITIONS
#define INCLUDED_ETR_DEFINITIONS

#define MAX_STOCK_NAME_LENGTH 15
#define MAX_BUYS_RECORDED 100
#define MAX_SELLS_RECORDED 100
#define MAX_TRADE_REQUEST_LENGTH 100
#define MAX_USER_NAME_LENGTH 20
#define MAX_USER_NAME_LENGTH 20

#endif
